# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'OTPViaWhatsapp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'TwilioSyncClient', '~> 2.0'
  pod 'TwilioVerify'
  # Pods for OTPViaWhatsapp


  target 'OTPViaWhatsappTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'OTPViaWhatsappUITests' do
    # Pods for testing
  end

end
